### ISSUE TITLE
UI font

### ISSUE THREAD

**Issue by celsomiranda** [kenwheeler/brogrammer-ui#1]
Hello.

This UI theme looks good, but the font defaults to 'Times New Roman' on Windows.

I've included a screenshot.
![brogrammer](https://cloud.githubusercontent.com/assets/769237/5600851/a1aded90-92dc-11e4-9042-3ccbc3460d78.PNG)

I've tried changing the LESS variable to another font but it's still too small to read properly.

Let me know how can I help you further.

Thanks in advance.

**Comment by braver** [comment]
Yeah, the Monaco, monotype (in ui-variables) is not going to work: only OSX has Monaco and Monotype is a foundry, not a font (you're looking for monospace here) ;)
